#!/usr/bin/env python

import sys

from rqt_robot_ctrl_gui.my_module import MyPlugin
from rqt_gui.main import Main

plugin = 'rqt_robot_ctrl_gui'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
